// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: cmd/macrod/schema/macrod.proto

package schema

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Macrod_CreateFoodListing_FullMethodName = "/schema.Macrod/CreateFoodListing"
	Macrod_GetFoodListing_FullMethodName    = "/schema.Macrod/GetFoodListing"
	Macrod_UpdateFoodListing_FullMethodName = "/schema.Macrod/UpdateFoodListing"
	Macrod_CreateMeal_FullMethodName        = "/schema.Macrod/CreateMeal"
	Macrod_AddFoodToMeal_FullMethodName     = "/schema.Macrod/AddFoodToMeal"
	Macrod_GetMeal_FullMethodName           = "/schema.Macrod/GetMeal"
	Macrod_Version_FullMethodName           = "/schema.Macrod/Version"
)

// MacrodClient is the client API for Macrod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MacrodClient interface {
	CreateFoodListing(ctx context.Context, in *FoodListing, opts ...grpc.CallOption) (*FoodListing, error)
	GetFoodListing(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*FoodListing, error)
	UpdateFoodListing(ctx context.Context, in *FoodListing, opts ...grpc.CallOption) (*FoodListing, error)
	CreateMeal(ctx context.Context, in *Meal, opts ...grpc.CallOption) (*Meal, error)
	AddFoodToMeal(ctx context.Context, in *UpdateMealRequest, opts ...grpc.CallOption) (*Meal, error)
	GetMeal(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Meal, error)
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type macrodClient struct {
	cc grpc.ClientConnInterface
}

func NewMacrodClient(cc grpc.ClientConnInterface) MacrodClient {
	return &macrodClient{cc}
}

func (c *macrodClient) CreateFoodListing(ctx context.Context, in *FoodListing, opts ...grpc.CallOption) (*FoodListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoodListing)
	err := c.cc.Invoke(ctx, Macrod_CreateFoodListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macrodClient) GetFoodListing(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*FoodListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoodListing)
	err := c.cc.Invoke(ctx, Macrod_GetFoodListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macrodClient) UpdateFoodListing(ctx context.Context, in *FoodListing, opts ...grpc.CallOption) (*FoodListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoodListing)
	err := c.cc.Invoke(ctx, Macrod_UpdateFoodListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macrodClient) CreateMeal(ctx context.Context, in *Meal, opts ...grpc.CallOption) (*Meal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Meal)
	err := c.cc.Invoke(ctx, Macrod_CreateMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macrodClient) AddFoodToMeal(ctx context.Context, in *UpdateMealRequest, opts ...grpc.CallOption) (*Meal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Meal)
	err := c.cc.Invoke(ctx, Macrod_AddFoodToMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macrodClient) GetMeal(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Meal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Meal)
	err := c.cc.Invoke(ctx, Macrod_GetMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macrodClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, Macrod_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MacrodServer is the server API for Macrod service.
// All implementations must embed UnimplementedMacrodServer
// for forward compatibility.
type MacrodServer interface {
	CreateFoodListing(context.Context, *FoodListing) (*FoodListing, error)
	GetFoodListing(context.Context, *wrapperspb.StringValue) (*FoodListing, error)
	UpdateFoodListing(context.Context, *FoodListing) (*FoodListing, error)
	CreateMeal(context.Context, *Meal) (*Meal, error)
	AddFoodToMeal(context.Context, *UpdateMealRequest) (*Meal, error)
	GetMeal(context.Context, *wrapperspb.StringValue) (*Meal, error)
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedMacrodServer()
}

// UnimplementedMacrodServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMacrodServer struct{}

func (UnimplementedMacrodServer) CreateFoodListing(context.Context, *FoodListing) (*FoodListing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFoodListing not implemented")
}
func (UnimplementedMacrodServer) GetFoodListing(context.Context, *wrapperspb.StringValue) (*FoodListing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFoodListing not implemented")
}
func (UnimplementedMacrodServer) UpdateFoodListing(context.Context, *FoodListing) (*FoodListing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFoodListing not implemented")
}
func (UnimplementedMacrodServer) CreateMeal(context.Context, *Meal) (*Meal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMeal not implemented")
}
func (UnimplementedMacrodServer) AddFoodToMeal(context.Context, *UpdateMealRequest) (*Meal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFoodToMeal not implemented")
}
func (UnimplementedMacrodServer) GetMeal(context.Context, *wrapperspb.StringValue) (*Meal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeal not implemented")
}
func (UnimplementedMacrodServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedMacrodServer) mustEmbedUnimplementedMacrodServer() {}
func (UnimplementedMacrodServer) testEmbeddedByValue()                {}

// UnsafeMacrodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MacrodServer will
// result in compilation errors.
type UnsafeMacrodServer interface {
	mustEmbedUnimplementedMacrodServer()
}

func RegisterMacrodServer(s grpc.ServiceRegistrar, srv MacrodServer) {
	// If the following call pancis, it indicates UnimplementedMacrodServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Macrod_ServiceDesc, srv)
}

func _Macrod_CreateFoodListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodListing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacrodServer).CreateFoodListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Macrod_CreateFoodListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacrodServer).CreateFoodListing(ctx, req.(*FoodListing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Macrod_GetFoodListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacrodServer).GetFoodListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Macrod_GetFoodListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacrodServer).GetFoodListing(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Macrod_UpdateFoodListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodListing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacrodServer).UpdateFoodListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Macrod_UpdateFoodListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacrodServer).UpdateFoodListing(ctx, req.(*FoodListing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Macrod_CreateMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacrodServer).CreateMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Macrod_CreateMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacrodServer).CreateMeal(ctx, req.(*Meal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Macrod_AddFoodToMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacrodServer).AddFoodToMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Macrod_AddFoodToMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacrodServer).AddFoodToMeal(ctx, req.(*UpdateMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Macrod_GetMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacrodServer).GetMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Macrod_GetMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacrodServer).GetMeal(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Macrod_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacrodServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Macrod_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacrodServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Macrod_ServiceDesc is the grpc.ServiceDesc for Macrod service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Macrod_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schema.Macrod",
	HandlerType: (*MacrodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFoodListing",
			Handler:    _Macrod_CreateFoodListing_Handler,
		},
		{
			MethodName: "GetFoodListing",
			Handler:    _Macrod_GetFoodListing_Handler,
		},
		{
			MethodName: "UpdateFoodListing",
			Handler:    _Macrod_UpdateFoodListing_Handler,
		},
		{
			MethodName: "CreateMeal",
			Handler:    _Macrod_CreateMeal_Handler,
		},
		{
			MethodName: "AddFoodToMeal",
			Handler:    _Macrod_AddFoodToMeal_Handler,
		},
		{
			MethodName: "GetMeal",
			Handler:    _Macrod_GetMeal_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Macrod_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/macrod/schema/macrod.proto",
}
